import 'package:infinibook_flutter/models/book.dart';
import 'package:infinibook_flutter/models/user.dart';
import '../globals.dart' as globals;

class DummyBooks {
  List<Book> books = [
    Book(
        imagePath: 'assets/Books/A Game of Thrones_2.jpeg',
        name: 'A Game of Thrones',
        author: 'George R.R. Martin',
        language: 'English',
        genres: 'Novel, High fantasy, Fantasy Fiction, Political fiction',
        pages: 694),
    Book(
        imagePath: 'assets/Books/A Game of Thrones.jpg',
        name: 'A Game of Thrones',
        author: 'George R.R. Martin',
        language: 'English',
        genres: 'Novel, High fantasy, Fantasy Fiction, Political fiction',
        pages: 694),
    Book(
        imagePath: 'assets/Books/Dune_4.jpg',
        name: 'Dune',
        author: 'Frank Herbert',
        language: 'English',
        genres: 'Science fiction',
        pages: 869),
    Book(
        imagePath: 'assets/Books/Dune_6.jpg',
        name: 'Dune',
        author: 'Frank Herbert',
        language: 'English',
        genres: 'Science fiction',
        pages: 592),
    Book(
        imagePath: 'assets/Books/Dune_3.jpg',
        name: 'Dune Messiah',
        author: 'Frank Herbert',
        language: 'English',
        genres: 'Science fiction',
        pages: 304),
    Book(
        imagePath: 'assets/Books/Dune_3.jpg',
        name: 'Dune Messiah',
        author: 'Frank Herbert',
        language: 'English',
        genres: 'Science fiction',
        pages: 304),
    Book(
        imagePath: 'assets/Books/Dune_5.jpg',
        name: 'Dune: Deluxe Hardcover',
        author: 'Frank Herbert',
        language: 'English',
        genres: 'Science fiction',
        pages: 688),
    Book(
        imagePath: 'assets/Books/Dune_1.jpg',
        name: 'Dune (Barnes & Noble Collectible Editions)',
        author: 'Frank Herbert',
        language: 'English',
        genres: 'Science fiction',
        pages: 576),
    Book(
        imagePath: 'assets/Books/Dune_8.jpg',
        name: 'Dune',
        author: 'Frank Herbert',
        language: 'English',
        genres: 'Science fiction',
        pages: 528),
    Book(
        imagePath: 'assets/Books/Dune_2.jpg',
        name: 'Dune',
        author: 'Frank Herbert',
        language: 'English',
        genres: 'Science fiction',
        pages: 528),
    Book(
        imagePath: 'assets/Books/Dune_8.jpg',
        name: 'Dune',
        author: 'Frank Herbert',
        language: 'English',
        genres: 'Science fiction',
        pages: 528),
    Book(
        imagePath: 'assets/Books/Dune_9.jpg',
        name: 'Dune',
        author: 'Frank Herbert',
        language: 'English',
        genres: 'Science fiction',
        pages: 528),
    Book(
        imagePath: 'assets/Books/Dune_10.jpg',
        name: 'Dune',
        author: 'Frank Herbert',
        language: 'English',
        genres: 'Science fiction',
        pages: 528),
    Book(
        imagePath: 'assets/Books/Lord of the Rings Fellowship of the Ring.jpeg',
        name: 'Lord of the Rings:The Fellowship of the Ring',
        author: 'J.R.R. Tolkien',
        language: 'English',
        genres: 'Fantasy',
        pages: 531),
    Book(
        imagePath: 'assets/Books/Fifty Shades of Grey.jpg',
        name: 'Fifty Shades of Grey',
        author: 'E.L. James',
        language: 'English',
        genres: 'Novel, Romance novel, Fiction, Erotic romance novel',
        pages: 514),
    Book(
        imagePath: 'assets/Books/Five Feet Apart.jpg',
        name: 'Five Feet Apart',
        author: 'Rachael Lippincott',
        language: 'English',
        genres: 'Adult Fiction',
        pages: 288),
    Book(
        imagePath: 'assets/Books/Fortress of Blood.jpg',
        name: 'Fortress of Blood',
        author: 'L. D. Goffigan',
        language: 'English',
        genres: 'action-adventure, romance, mystery, paranormal twist',
        pages: 258),
    Book(
        imagePath: 'assets/Books/Harry Potter and the Cursed Child.jpg',
        name: 'Harry Potter and the Cursed Child',
        author: 'J.K. Rowling',
        language: 'English',
        genres: 'Fantasy, Drama',
        pages: 328),
    Book(
        imagePath: 'assets/Books/Harry Potter and the Order of Phoenix.jpg',
        name: 'Harry Potter and the Order of Phoenix',
        author: 'J.K. Rowling',
        language: 'English',
        genres: 'Fantasy, Drama',
        pages: 766),
    Book(
        imagePath: 'assets/Books/Jaws.jpg',
        name: 'Jaws',
        author: 'Peter Benchley',
        language: 'English',
        genres: 'Thriller',
        pages: 278),
    Book(
        imagePath: 'assets/Books/Jurassic Park.jpg',
        name: 'Jurassic Park',
        author: 'Michael Crichton',
        language: 'English',
        genres: 'Science fiction',
        pages: 448),
    Book(
        imagePath: 'assets/Books/Sin Eater.jpg',
        name: 'The Sin Eater',
        author: 'Megan Campisi',
        language: 'English',
        genres: 'Novel, Fiction, Historical',
        pages: 272),
    Book(
        imagePath: 'assets/Books/Tess of the Road.jpg',
        name: 'Tess of the Road',
        author: 'Rachel Hartman',
        language: 'English',
        genres: 'Young adult fiction, Fantasy Fiction',
        pages: 520),
    Book(
        imagePath: 'assets/Books/The Great Gatsby.jpg',
        name: 'The Great Gatsby',
        author: 'F. Scott Fitzgerald',
        language: 'English',
        genres: 'Tragedy',
        pages: 208),
    Book(
        imagePath: 'assets/Books/The Snowman.jpg',
        name: 'The Snowman',
        author: 'Jo Nesbo',
        language: 'English',
        genres: 'Crime fiction, Horror fiction',
        pages: 438),
    Book(
        imagePath: 'assets/Books/The Stranger.jpg',
        name: 'The Stranger',
        author: 'Albert Camus',
        language: 'English',
        genres: 'Philosophical novel',
        pages: 159),
    Book(
        imagePath: 'assets/Books/To Kill A Mockingbird.jpg',
        name: 'To Kill A Mockingbird',
        author: 'Harper Lee',
        language: 'English',
        genres: 'Coming-of-age story, Bildungsroman',
        pages: 281),
    Book(
        imagePath: 'assets/Books/Very Nice.jpg',
        name: 'Very Nice',
        author: 'Marcy Dermansky',
        language: 'English',
        genres: 'Humor, Dark comedy, Domestic Fiction',
        pages: 290),
    Book(
        imagePath: 'assets/Books/Yhe Subtle Art of Not Giving a Fuck.jpg',
        name: 'The Subtle Art of Not Giving a Fuck',
        author: ' Mark Manson',
        language: 'English',
        genres: 'Self-help book',
        pages: 224)
  ];
}

class DummyData {
  List<User> users = [
    User(
        imagePath: 'assets/images/chris_500.jpeg',
        name: 'Chris Marres',
        email: 'chris.marres@gmail.com',
        books: 10,
        followers: 4,
        following: 2,
        booksList: <Book>[
          globals.dummyBooks.books[0],
          globals.dummyBooks.books[1],
          globals.dummyBooks.books[22],
          globals.dummyBooks.books[13],
          globals.dummyBooks.books[14],
          globals.dummyBooks.books[15],
          globals.dummyBooks.books[26],
          globals.dummyBooks.books[7],
          globals.dummyBooks.books[18],
          globals.dummyBooks.books[23],
        ]),
    User(
        imagePath: 'assets/Faces/Themis Tsaprazlis.jpg',
        name: 'Themis Tsaprazlis',
        email: 'tim.tsapras@gmail.com',
        books: 10,
        followers: 5,
        following: 3,
        booksList: <Book>[
          globals.dummyBooks.books[0],
          globals.dummyBooks.books[13],
          globals.dummyBooks.books[4],
          globals.dummyBooks.books[28],
          globals.dummyBooks.books[14],
          globals.dummyBooks.books[5],
          globals.dummyBooks.books[16],
          globals.dummyBooks.books[7],
          globals.dummyBooks.books[8],
          globals.dummyBooks.books[23],
        ]),
    User(
        imagePath: 'assets/Faces/Amanda Terry.jpg',
        name: 'Amanda Terry',
        email: 'amanda.terry@hotmail.com',
        books: 5,
        followers: 2,
        following: 3,
        booksList: <Book>[
          globals.dummyBooks.books[5],
          globals.dummyBooks.books[16],
          globals.dummyBooks.books[22],
          globals.dummyBooks.books[8],
          globals.dummyBooks.books[13],
        ]),
    User(
        imagePath: 'assets/Faces/Christofer Kross.jpg',
        name: 'Christofer Kross',
        email: 'chriskross@gmail.com',
        books: 3,
        followers: 4,
        following: 3,
        booksList: <Book>[
          globals.dummyBooks.books[2],
          globals.dummyBooks.books[12],
          globals.dummyBooks.books[27],
        ]),
    User(
        imagePath: 'assets/Faces/George Pagonis.jpg',
        name: 'George Pagonis',
        email: 'gpag@yahoo.com',
        books: 7,
        followers: 2,
        following: 1,
        booksList: <Book>[
          globals.dummyBooks.books[0],
          globals.dummyBooks.books[3],
          globals.dummyBooks.books[24],
          globals.dummyBooks.books[9],
          globals.dummyBooks.books[14],
          globals.dummyBooks.books[15],
          globals.dummyBooks.books[16],
        ]),
    User(
        imagePath: 'assets/Faces/Maria Kosta.jpg',
        name: 'Maria Kosta',
        email: 'mariakk@gmail.com',
        books: 8,
        followers: 4,
        following: 6,
        booksList: <Book>[
          globals.dummyBooks.books[5],
          globals.dummyBooks.books[20],
          globals.dummyBooks.books[8],
          globals.dummyBooks.books[3],
          globals.dummyBooks.books[19],
          globals.dummyBooks.books[13],
          globals.dummyBooks.books[16],
          globals.dummyBooks.books[24],
        ]),
    User(
        imagePath: 'assets/Faces/Mingxuan Ze.jpg',
        name: 'Mingxuan Ze',
        email: 'liu.min@gmail.com',
        books: 4,
        followers: 2,
        following: 2,
        booksList: <Book>[
          globals.dummyBooks.books[26],
          globals.dummyBooks.books[7],
          globals.dummyBooks.books[8],
          globals.dummyBooks.books[13],
        ]),
    User(
        imagePath: 'assets/Faces/Nina Brown.jpg',
        name: 'Nina Brown',
        email: 'nnbrown@hotmail.com',
        books: 5,
        followers: 3,
        following: 3,
        booksList: <Book>[
          globals.dummyBooks.books[14],
          globals.dummyBooks.books[17],
          globals.dummyBooks.books[23],
          globals.dummyBooks.books[18],
          globals.dummyBooks.books[28],
        ]),
    User(
        imagePath: 'assets/Faces/Tatiana Goldberg.jpg',
        name: 'Tatiana Goldberg',
        email: 'goldie@gmail.com',
        books: 7,
        followers: 4,
        following: 4,
        booksList: <Book>[
          globals.dummyBooks.books[3],
          globals.dummyBooks.books[14],
          globals.dummyBooks.books[15],
          globals.dummyBooks.books[16],
          globals.dummyBooks.books[7],
          globals.dummyBooks.books[8],
          globals.dummyBooks.books[13],
        ]),
    User(
        imagePath: 'assets/Faces/Tim Vogel.jpg',
        name: 'Tim Vogel',
        email: 'tvogelt@yahoo.com',
        books: 5,
        followers: 2,
        following: 2,
        booksList: <Book>[
          globals.dummyBooks.books[6],
          globals.dummyBooks.books[25],
          globals.dummyBooks.books[19],
          globals.dummyBooks.books[21],
          globals.dummyBooks.books[13],
        ]),
  ];
}
